"""create table

Revision ID: 66bd9998dfae
Revises: 
Create Date: 2023-12-27 15:49:08.734626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bd9998dfae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defectId', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('interested_party', sa.String(), nullable=True),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(desc) >= 30'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defect')
    # ### end Alembic commands ###
